/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignUpImport } from './routes/sign-up'
import { Route as SignInImport } from './routes/sign-in'
import { Route as PieceLibraryImport } from './routes/pieceLibrary'
import { Route as IndexImport } from './routes/index'
import { Route as PiecePieceIdImport } from './routes/piece.$pieceId'

// Create/Update Routes

const SignUpRoute = SignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const SignInRoute = SignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const PieceLibraryRoute = PieceLibraryImport.update({
  id: '/pieceLibrary',
  path: '/pieceLibrary',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PiecePieceIdRoute = PiecePieceIdImport.update({
  id: '/piece/$pieceId',
  path: '/piece/$pieceId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/pieceLibrary': {
      id: '/pieceLibrary'
      path: '/pieceLibrary'
      fullPath: '/pieceLibrary'
      preLoaderRoute: typeof PieceLibraryImport
      parentRoute: typeof rootRoute
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInImport
      parentRoute: typeof rootRoute
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpImport
      parentRoute: typeof rootRoute
    }
    '/piece/$pieceId': {
      id: '/piece/$pieceId'
      path: '/piece/$pieceId'
      fullPath: '/piece/$pieceId'
      preLoaderRoute: typeof PiecePieceIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pieceLibrary': typeof PieceLibraryRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/piece/$pieceId': typeof PiecePieceIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pieceLibrary': typeof PieceLibraryRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/piece/$pieceId': typeof PiecePieceIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/pieceLibrary': typeof PieceLibraryRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/piece/$pieceId': typeof PiecePieceIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pieceLibrary' | '/sign-in' | '/sign-up' | '/piece/$pieceId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pieceLibrary' | '/sign-in' | '/sign-up' | '/piece/$pieceId'
  id:
    | '__root__'
    | '/'
    | '/pieceLibrary'
    | '/sign-in'
    | '/sign-up'
    | '/piece/$pieceId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PieceLibraryRoute: typeof PieceLibraryRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  PiecePieceIdRoute: typeof PiecePieceIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PieceLibraryRoute: PieceLibraryRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  PiecePieceIdRoute: PiecePieceIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/pieceLibrary",
        "/sign-in",
        "/sign-up",
        "/piece/$pieceId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/pieceLibrary": {
      "filePath": "pieceLibrary.tsx"
    },
    "/sign-in": {
      "filePath": "sign-in.tsx"
    },
    "/sign-up": {
      "filePath": "sign-up.tsx"
    },
    "/piece/$pieceId": {
      "filePath": "piece.$pieceId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
