/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PieceLibraryImport } from './routes/pieceLibrary'
import { Route as PieceImport } from './routes/piece'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const PieceLibraryRoute = PieceLibraryImport.update({
  id: '/pieceLibrary',
  path: '/pieceLibrary',
  getParentRoute: () => rootRoute,
} as any)

const PieceRoute = PieceImport.update({
  id: '/piece',
  path: '/piece',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/piece': {
      id: '/piece'
      path: '/piece'
      fullPath: '/piece'
      preLoaderRoute: typeof PieceImport
      parentRoute: typeof rootRoute
    }
    '/pieceLibrary': {
      id: '/pieceLibrary'
      path: '/pieceLibrary'
      fullPath: '/pieceLibrary'
      preLoaderRoute: typeof PieceLibraryImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/piece': typeof PieceRoute
  '/pieceLibrary': typeof PieceLibraryRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/piece': typeof PieceRoute
  '/pieceLibrary': typeof PieceLibraryRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/piece': typeof PieceRoute
  '/pieceLibrary': typeof PieceLibraryRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/piece' | '/pieceLibrary'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/piece' | '/pieceLibrary'
  id: '__root__' | '/' | '/piece' | '/pieceLibrary'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PieceRoute: typeof PieceRoute
  PieceLibraryRoute: typeof PieceLibraryRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PieceRoute: PieceRoute,
  PieceLibraryRoute: PieceLibraryRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/piece",
        "/pieceLibrary"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/piece": {
      "filePath": "piece.tsx"
    },
    "/pieceLibrary": {
      "filePath": "pieceLibrary.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
