/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PieceLibraryImport } from './routes/pieceLibrary'
import { Route as PieceImport } from './routes/piece'
import { Route as AppImport } from './routes/_app'
import { Route as IndexImport } from './routes/index'
import { Route as AuthCallbackImport } from './routes/auth.callback'

// Create/Update Routes

const PieceLibraryRoute = PieceLibraryImport.update({
  id: '/pieceLibrary',
  path: '/pieceLibrary',
  getParentRoute: () => rootRoute,
} as any)

const PieceRoute = PieceImport.update({
  id: '/piece',
  path: '/piece',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthCallbackRoute = AuthCallbackImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/piece': {
      id: '/piece'
      path: '/piece'
      fullPath: '/piece'
      preLoaderRoute: typeof PieceImport
      parentRoute: typeof rootRoute
    }
    '/pieceLibrary': {
      id: '/pieceLibrary'
      path: '/pieceLibrary'
      fullPath: '/pieceLibrary'
      preLoaderRoute: typeof PieceLibraryImport
      parentRoute: typeof rootRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AppRoute
  '/piece': typeof PieceRoute
  '/pieceLibrary': typeof PieceLibraryRoute
  '/auth/callback': typeof AuthCallbackRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AppRoute
  '/piece': typeof PieceRoute
  '/pieceLibrary': typeof PieceLibraryRoute
  '/auth/callback': typeof AuthCallbackRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_app': typeof AppRoute
  '/piece': typeof PieceRoute
  '/pieceLibrary': typeof PieceLibraryRoute
  '/auth/callback': typeof AuthCallbackRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/piece' | '/pieceLibrary' | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/piece' | '/pieceLibrary' | '/auth/callback'
  id: '__root__' | '/' | '/_app' | '/piece' | '/pieceLibrary' | '/auth/callback'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  PieceRoute: typeof PieceRoute
  PieceLibraryRoute: typeof PieceLibraryRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  PieceRoute: PieceRoute,
  PieceLibraryRoute: PieceLibraryRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_app",
        "/piece",
        "/pieceLibrary",
        "/auth/callback"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_app": {
      "filePath": "_app.tsx"
    },
    "/piece": {
      "filePath": "piece.tsx"
    },
    "/pieceLibrary": {
      "filePath": "pieceLibrary.tsx"
    },
    "/auth/callback": {
      "filePath": "auth.callback.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
